using System.Globalization;

namespace AIVES.DTO.Localization;

/// <summary>
/// Translation catalog. English source text is the key and the fallback, so any key that is
/// missing here still renders in English instead of showing a resource identifier.
/// </summary>
internal static class AppText
{
    private static readonly Dictionary<string, string> Vietnamese = new(StringComparer.OrdinalIgnoreCase)
    {
        // Navigation and layout
        ["Work space"] = "Không gian làm việc",
        ["System"] = "Hệ thống",
        ["Overview"] = "Tổng quan",
        ["Questions & rubric"] = "Câu hỏi & rubric",
        ["Exams"] = "Kỳ thi",
        ["Under construction"] = "Đang xây dựng",
        ["AI exam room"] = "Phòng thi AI",
        ["Grading"] = "Chấm điểm",
        ["Reports"] = "Báo cáo",
        ["Users"] = "Người dùng",
        ["System check"] = "Kiểm tra hệ thống",
        ["Admin"] = "Quản trị",
        ["Data policy"] = "Chính sách dữ liệu",
        ["AI-powered Viva Exam System"] = "Hệ thống thi vấn đáp thông minh AI",
        ["AI-powered viva exam system"] = "Hệ thống thi vấn đáp thông minh có sử dụng AI",
        ["Secure access for lecturers and students"] = "Xác thực an toàn cho giảng viên và sinh viên",
        ["Sign in"] = "Đăng nhập",
        ["Sign out"] = "Đăng xuất",

        // Home
        ["Viva exam orchestration"] = "Điều hành thi vấn đáp",
        ["Prepare questions, run adaptive interviews and approve results in one auditable workflow."] = "Chuẩn bị câu hỏi, tổ chức phỏng vấn thích ứng và duyệt kết quả trong một quy trình có thể kiểm chứng.",
        ["Open bank"] = "Mở ngân hàng",
        ["Create question"] = "Tạo câu hỏi",
        ["Operating workflow"] = "Quy trình vận hành",
        ["From course material to grade decision"] = "Từ học liệu đến quyết định điểm",
        ["1 module ready"] = "1 module sẵn sàng",
        ["Question & rubric preparation"] = "Chuẩn bị câu hỏi & rubric",
        ["Create, classify Bloom level and approve questions before use."] = "Tạo, phân loại Bloom và duyệt câu hỏi trước khi sử dụng.",
        ["Ready"] = "Sẵn sàng",
        ["Planned"] = "Kế hoạch",
        ["Exam & scheduling"] = "Lập kỳ thi & lịch thi",
        ["Attach a subject, the participant list and a time limit."] = "Gắn môn học, danh sách sinh viên và giới hạn thời gian.",
        ["Adaptive interview"] = "Phỏng vấn thích ứng",
        ["STT, TTS and follow-up questions driven by the answer."] = "STT, TTS và câu hỏi đào sâu theo nội dung trả lời.",
        ["Grade review & evidence"] = "Duyệt điểm & bằng chứng",
        ["Reconcile transcript, rubric and the lecturer decision."] = "Đối chiếu transcript, rubric và quyết định của giảng viên.",
        ["The lecturer always decides"] = "Giảng viên luôn là người quyết định",
        ["Main question"] = "Câu hỏi chính",
        ["Choose by subject, Bloom level and rubric."] = "Chọn theo môn học, Bloom và rubric.",
        ["Answer recognition"] = "Nhận dạng câu trả lời",
        ["Turn speech into an auditable transcript."] = "Chuyển giọng nói thành transcript có lưu vết.",
        ["Adaptive probing"] = "Hỏi xoáy thích ứng",
        ["Clarify missing, vague or contradictory ideas."] = "Làm rõ ý thiếu, mơ hồ hoặc mâu thuẫn.",
        ["Rubric suggestions"] = "Gợi ý theo rubric",
        ["AI proposes; the lecturer approves and finalises the grade."] = "AI đề xuất; giảng viên duyệt và chốt điểm.",
        ["AIVES feature groups"] = "Các nhóm chức năng AIVES",
        ["Question bank"] = "Ngân hàng câu hỏi",
        ["CRUD for questions, Bloom levels and rubrics."] = "CRUD câu hỏi, mức Bloom và rubric.",
        ["Exams & scheduling"] = "Kỳ thi & lịch thi",
        ["Sessions, participants and question selection."] = "Phiên thi, thí sinh và chọn câu hỏi.",
        ["AI interview core"] = "Lõi phỏng vấn AI",
        ["STT, TTS and adaptive follow-up."] = "STT, TTS và adaptive follow-up.",
        ["Grading support"] = "Hỗ trợ chấm điểm",
        ["Reconcile transcripts against rubrics."] = "Đối chiếu transcript với rubric.",
        ["Supervision"] = "Giám sát",
        ["Recordings, logs and change history."] = "Bản ghi, log và lịch sử thay đổi.",
        ["Feedback & reports"] = "Phản hồi & báo cáo",
        ["Per question scores and class statistics."] = "Điểm từng câu và thống kê lớp.",
        ["Administration"] = "Quản trị",
        ["Accounts, permissions and language."] = "Tài khoản, phân quyền và ngôn ngữ.",

        // Account
        ["Resume your academic workspace"] = "Tiếp tục phiên làm việc học thuật",
        ["Access the question bank, AI exam room and assessment records with your verified account."] = "Truy cập ngân hàng câu hỏi, phòng thi AI và hồ sơ đánh giá bằng tài khoản đã xác minh.",
        ["Email is verified before sign in"] = "Email được xác minh trước khi đăng nhập",
        ["Temporary lock after repeated failed attempts"] = "Khóa tạm thời khi thử sai nhiều lần",
        ["Google OAuth never shares your password with AIVES"] = "Google OAuth không chia sẻ mật khẩu với AIVES",
        ["Use the Gmail account you registered with."] = "Nhập tài khoản Gmail đã đăng ký.",
        ["Password"] = "Mật khẩu",
        ["Enter your password"] = "Nhập mật khẩu",
        ["Keep me signed in on this device"] = "Ghi nhớ đăng nhập trên thiết bị này",
        ["or"] = "hoặc",
        ["Sign in with Google"] = "Đăng nhập với Google",
        ["No account yet?"] = "Chưa có tài khoản?",
        ["Register with Gmail"] = "Đăng ký bằng Gmail",
        ["Create an AIVES account"] = "Tạo tài khoản AIVES",
        ["Register"] = "Đăng ký",
        ["Register and send code"] = "Đăng ký và gửi mã",
        ["Use a Gmail address you can access."] = "Sử dụng địa chỉ Gmail bạn có quyền truy cập.",
        ["Full name"] = "Họ và tên",
        ["Confirm password"] = "Xác nhận mật khẩu",
        ["Continue with Google"] = "Tiếp tục với Google",
        ["Already have an account?"] = "Đã có tài khoản?",
        ["New account"] = "Tài khoản mới",
        ["Verified identity"] = "Xác thực danh tính",
        ["Email verification"] = "Xác minh email",
        ["Enter your verification code"] = "Nhập mã xác minh",
        ["A 6 digit code was sent to {0}. The code expires after 10 minutes."] = "Mã 6 chữ số đã được gửi đến {0}. Mã hết hạn sau 10 phút.",
        ["Verification code"] = "Mã xác minh",
        ["Verify account"] = "Xác minh tài khoản",
        ["Resend code"] = "Gửi lại mã",

        // Question bank
        ["Manage viva questions, Bloom taxonomy levels and scoring rubrics."] = "Quản lý câu hỏi vấn đáp, mức độ nhận thức và rubric đánh giá.",
        ["All questions"] = "Tất cả câu hỏi",
        ["{0} questions in the database"] = "{0} câu hỏi trong cơ sở dữ liệu",
        ["Question"] = "Câu hỏi",
        ["Topic"] = "Chủ đề",
        ["Bloom level"] = "Mức Bloom",
        ["Status"] = "Trạng thái",
        ["Actions"] = "Thao tác",
        ["View"] = "Xem",
        ["Edit"] = "Sửa",
        ["Delete"] = "Xóa",
        ["Active"] = "Hoạt động",
        ["Hidden"] = "Tạm ẩn",
        ["Created {0}"] = "Tạo ngày {0}",
        ["The bank has no questions yet"] = "Ngân hàng chưa có câu hỏi",
        ["Create your first structured viva question to get started."] = "Tạo câu hỏi vấn đáp có cấu trúc đầu tiên để bắt đầu.",
        ["Create the first question"] = "Tạo câu hỏi đầu tiên",
        ["Create a viva question"] = "Tạo câu hỏi vấn đáp",
        ["Write a clear question and attach its Bloom level and scoring rubric."] = "Xây dựng câu hỏi rõ ràng, gắn mức độ Bloom và rubric chấm điểm.",
        ["Can be generated with AI"] = "Có thể sinh bằng AI",
        ["Question content"] = "Nội dung câu hỏi",
        ["Enter the main question and the ideas the answer should cover."] = "Nhập câu hỏi chính và các ý cần có trong câu trả lời.",
        ["Viva question"] = "Câu hỏi vấn đáp",
        ["Example: Explain polymorphism and give one real world example."] = "Ví dụ: Hãy giải thích tính đa hình và đưa ra một ví dụ thực tế?",
        ["At least 10 characters. A good question targets one assessable capability."] = "Tối thiểu 10 ký tự. Câu hỏi nên tập trung vào một năng lực cần đánh giá.",
        ["Expected answer / key points"] = "Đáp án mong đợi / ý chính",
        ["List the concepts and key points the student should cover..."] = "Liệt kê khái niệm và các ý quan trọng mà sinh viên cần trình bày...",
        ["Assessment setup"] = "Khung đánh giá",
        ["Choose the Bloom level and how the answer will be scored."] = "Xác định mức độ nhận thức và phương pháp chấm điểm.",
        ["Scoring rubric"] = "Rubric chấm điểm",
        ["Select a Bloom level"] = "Chọn mức độ Bloom",
        ["Select a rubric"] = "Chọn rubric",
        ["Classification & status"] = "Phân loại & trạng thái",
        ["Attach a subject, topic and display order."] = "Gắn môn học, chủ đề và thứ tự hiển thị.",
        ["Subject / topic"] = "Môn học / chủ đề",
        ["Example: Object oriented programming"] = "Ví dụ: Lập trình hướng đối tượng",
        ["Display order"] = "Thứ tự hiển thị",
        ["Publish to the official bank"] = "Đưa vào ngân hàng chính thức",
        ["This question can be used in an examination"] = "Câu hỏi có thể được sử dụng trong kỳ thi",
        ["Cancel"] = "Hủy",
        ["Save question"] = "Lưu câu hỏi",
        ["Save changes"] = "Lưu thay đổi",
        ["Edit question"] = "Sửa câu hỏi",
        ["Refine the content or update its evaluation settings."] = "Chỉnh sửa nội dung hoặc cập nhật thiết lập đánh giá.",
        ["Keep the prompt clear and measurable."] = "Giữ câu hỏi rõ ràng và có thể đo lường.",
        ["Assessment & organization"] = "Đánh giá & tổ chức",
        ["Update taxonomy, rubric and classification."] = "Cập nhật phân loại, rubric và cách gom nhóm.",
        ["Active question"] = "Câu hỏi đang hoạt động",
        ["Available for use in examinations"] = "Có thể sử dụng trong kỳ thi",
        ["Question #{0}"] = "Câu hỏi #{0}",
        ["Question details"] = "Chi tiết câu hỏi",
        ["Review the complete assessment setup."] = "Xem lại toàn bộ thiết lập đánh giá.",
        ["Back"] = "Quay lại",
        ["● Active"] = "● Hoạt động",
        ["○ Hidden"] = "○ Tạm ẩn",
        ["Not specified"] = "Chưa xác định",
        ["Expected answer"] = "Đáp án mong đợi",
        ["Updated {0}"] = "Cập nhật {0}",
        ["Delete question"] = "Xóa câu hỏi",
        ["Delete this question?"] = "Xóa câu hỏi này?",
        ["This action is permanent and cannot be undone."] = "Hành động này là vĩnh viễn và không thể hoàn tác.",
        ["Keep question"] = "Giữ câu hỏi",
        ["Yes, delete permanently"] = "Có, xóa vĩnh viễn",

        // AI exam room
        ["Generate questions with Gemini"] = "Tạo câu hỏi bằng Gemini",
        ["Generate a viva question set"] = "Tạo bộ câu hỏi vấn đáp",
        ["Gemini produces a structured draft for the lecturer to read, refine and approve before it enters an exam."] = "Gemini tạo bản nháp có cấu trúc để giảng viên đọc, chỉnh sửa và duyệt trước khi đưa vào kỳ thi.",
        ["Academic brief"] = "Yêu cầu học thuật",
        ["Subject"] = "Môn học",
        ["Topic to assess"] = "Chủ đề cần đánh giá",
        ["Example: Polymorphism and SOLID"] = "Ví dụ: Tính đa hình và SOLID",
        ["Learning outcomes / knowledge scope"] = "Chuẩn đầu ra / phạm vi kiến thức",
        ["Describe the concepts, skills or content limits Gemini should follow..."] = "Nêu các khái niệm, kỹ năng hoặc giới hạn nội dung Gemini cần bám theo...",
        ["Number of questions"] = "Số câu hỏi",
        ["Difficulty"] = "Mức độ",
        ["Balanced"] = "Cân bằng",
        ["Basic"] = "Cơ bản",
        ["Intermediate"] = "Trung bình",
        ["Advanced"] = "Nâng cao",
        ["Generate list"] = "Tạo danh sách",
        ["Suggested list"] = "Danh sách đề xuất",
        ["{0} questions"] = "{0} câu",
        ["No questions generated yet"] = "Chưa có câu hỏi được tạo",
        ["Fill in the academic brief on the left. The result includes the main question, expected answer, Bloom level and two follow up questions."] = "Điền yêu cầu học thuật ở bên trái. Kết quả sẽ gồm câu hỏi chính, đáp án mong đợi, mức Bloom và hai câu hỏi đào sâu.",
        ["AI draft · needs lecturer approval"] = "Bản nháp AI · cần giảng viên duyệt",
        ["Expected key points"] = "Ý chính mong đợi",
        ["Follow up questions"] = "Câu hỏi đào sâu",

        // Admin system check
        ["System configuration check"] = "Kiểm tra cấu hình hệ thống",
        ["Aggregated status of external services and the database. This page is restricted to administrators."] = "Tổng hợp trạng thái các dịch vụ ngoài và database. Trang này chỉ dành cho quản trị viên.",
        ["System healthy"] = "Hệ thống ổn định",
        ["Configuration incomplete"] = "Có cấu hình còn thiếu",
        ["Check again"] = "Kiểm tra lại",
        ["Missing / errors"] = "Thiếu / lỗi",
        ["Configuration needed before the feature runs"] = "Cần cấu hình để tính năng chạy được",
        ["Warnings"] = "Cảnh báo",
        ["Optional, but worth reviewing"] = "Không bắt buộc nhưng nên kiểm tra",
        ["Configured"] = "Đã cấu hình",
        ["Services ready to use"] = "Dịch vụ sẵn sàng sử dụng",
        ["Service status"] = "Trạng thái từng dịch vụ",
        ["{0} checks"] = "{0} mục",
        ["How to fix"] = "Cách khắc phục",
        ["SQL Server data"] = "Dữ liệu SQL Server",
        ["Connected"] = "Đã kết nối",
        ["Disconnected"] = "Mất kết nối",
        ["Server"] = "Máy chủ",
        ["Database"] = "Cơ sở dữ liệu",
        ["Pending migrations"] = "Migration chưa áp dụng",
        ["Accounts with verified email"] = "Tài khoản đã xác minh email",
        ["Questions in the bank"] = "Câu hỏi trong ngân hàng",
        ["Rubrics / Bloom levels"] = "Rubric / Mức Bloom",
        ["Could not read data from SQL Server."] = "Không đọc được dữ liệu từ SQL Server.",
        ["Internal counters stay at 0 until the connection succeeds."] = "Các chỉ số nội bộ sẽ hiển thị 0 cho tới khi kết nối thành công.",
        ["Updated at {0} UTC · Environment {1}"] = "Cập nhật lúc {0} UTC · Môi trường {1}",

        // Data policy
        ["AIVES stores the academic data required to prepare and run viva examinations: account details, question banks, rubrics and assessment records."] = "AIVES lưu trữ dữ liệu học thuật cần thiết để chuẩn bị và vận hành kỳ thi vấn đáp: thông tin tài khoản, ngân hàng câu hỏi, rubric và hồ sơ đánh giá.",
        ["Access is limited to verified accounts. System configuration and service credentials are only visible to administrators."] = "Quyền truy cập chỉ dành cho tài khoản đã xác minh. Cấu hình hệ thống và thông tin dịch vụ chỉ hiển thị với quản trị viên.",

        // Sign in and account errors
        ["The email or password is incorrect, or the account has not been verified."] = "Email hoặc mật khẩu không đúng, hoặc tài khoản chưa được xác minh.",
        ["The email or password is incorrect."] = "Email hoặc mật khẩu không đúng.",
        ["The account is temporarily locked after too many failed sign in attempts."] = "Tài khoản tạm khóa do đăng nhập sai nhiều lần.",
        ["This account is not allowed to sign in or requires additional verification."] = "Tài khoản này không được phép đăng nhập hoặc cần xác thực bổ sung.",
        ["The account was not found."] = "Không tìm thấy tài khoản.",
        ["Please use a @gmail.com address."] = "Vui lòng sử dụng địa chỉ @gmail.com.",
        ["The verification code cannot be sent right now. Please try again later or contact an administrator."] = "Không thể gửi mã xác minh lúc này. Vui lòng thử lại sau hoặc liên hệ quản trị viên.",
        ["The verification code could not be sent. Please try again."] = "Không thể gửi mã xác minh. Vui lòng kiểm tra cấu hình Gmail và thử lại.",
        ["The code is incorrect, expired, or you exceeded the number of attempts."] = "Mã không đúng, đã hết hạn hoặc vượt quá số lần thử.",
        ["Could not read the Google sign in information."] = "Không nhận được thông tin đăng nhập Google.",
        ["This account is locked out, not allowed to sign in, or needs additional verification."] = "Tài khoản bị khóa, chưa được phép đăng nhập hoặc cần xác thực bổ sung.",
        ["Google did not provide an email address."] = "Google chưa cung cấp email.",
        ["Something went wrong while processing your account. Please try again."] = "Đã có lỗi khi xử lý tài khoản. Vui lòng thử lại.",
        ["If the account is valid, a new code has been sent."] = "Nếu tài khoản hợp lệ, một mã mới đã được gửi.",
        ["Could not send the verification code. Please try again."] = "Không thể gửi mã xác minh. Vui lòng thử lại.",
        ["Please wait a minute before requesting a new code."] = "Vui lòng chờ một phút trước khi yêu cầu mã mới.",

        // Email sender
        ["The email service is not configured."] = "Dịch vụ gửi email chưa được cấu hình.",
        ["Your AIVES account verification code"] = "Mã xác minh tài khoản AIVES",

        // Gemini
        ["The number of questions must be between 1 and 10."] = "Số câu hỏi phải từ 1 đến 10.",
        ["The subject must be between 1 and 120 characters."] = "Môn học phải có từ 1 đến 120 ký tự.",
        ["The topic must be between 1 and 200 characters."] = "Chủ đề phải có từ 1 đến 200 ký tự.",
        ["Learning outcomes cannot exceed 2000 characters."] = "Chuẩn đầu ra không được vượt quá 2000 ký tự.",
        ["Gemini cannot generate questions right now. Check the API key, quota and configured model."] = "Gemini không thể tạo câu hỏi lúc này. Hãy kiểm tra API key, quota và model cấu hình.",
        ["Gemini did not return a valid question list. Try again with a more specific topic."] = "Gemini chưa trả về danh sách câu hỏi hợp lệ. Vui lòng thử lại với chủ đề cụ thể hơn.",
        ["Could not generate questions right now. Please try again later."] = "Không thể tạo câu hỏi lúc này. Vui lòng thử lại sau.",
        ["The AI question generator is temporarily unavailable. Please try again later."] = "Tính năng tạo câu hỏi bằng AI đang tạm thời không khả dụng. Vui lòng thử lại sau.",
        ["Something went wrong while generating questions. Please try again."] = "Đã có lỗi khi tạo câu hỏi. Vui lòng thử lại.",

        // Profile
        ["Profile"] = "Hồ sơ",
        ["Your profile"] = "Hồ sơ của bạn",
        ["Your AIVES account details and sign out options."] = "Thông tin tài khoản AIVES và tùy chọn đăng xuất của bạn.",
        ["Account"] = "Tài khoản",
        ["Identity"] = "Danh tính",
        ["Email verified"] = "Email đã xác minh",
        ["Email not verified"] = "Email chưa xác minh",
        ["Member since"] = "Thành viên từ",
        ["Role"] = "Vai trò",
        ["User"] = "Người dùng",
        ["Session"] = "Phiên làm việc",
        ["Sign out ends the current session on this device and returns you to the login page."] = "Đăng xuất kết thúc phiên làm việc hiện tại trên thiết bị này và đưa bạn trở lại trang đăng nhập.",
        ["Something went wrong while loading the profile. Please try again."] = "Đã có lỗi khi tải hồ sơ. Vui lòng thử lại.",

        // Question bank
        ["An error occurred while retrieving questions"] = "Đã có lỗi khi tải danh sách câu hỏi.",
        ["An error occurred while loading the form"] = "Đã có lỗi khi tải biểu mẫu.",
        ["Question '{0}...' created successfully"] = "Đã tạo câu hỏi '{0}...' thành công.",
        ["Question updated successfully"] = "Đã cập nhật câu hỏi thành công.",
        ["Question deleted successfully"] = "Đã xóa câu hỏi thành công.",
        ["An error occurred while creating the question"] = "Đã có lỗi khi tạo câu hỏi.",
        ["An error occurred while updating the question"] = "Đã có lỗi khi cập nhật câu hỏi.",
        ["An error occurred while deleting the question"] = "Đã có lỗi khi xóa câu hỏi."
    };

    public static string Resolve(string english)
    {
        if (string.IsNullOrEmpty(english))
            return english;

        if (CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("vi", StringComparison.OrdinalIgnoreCase)
            && Vietnamese.TryGetValue(english, out var translated))
            return translated;

        return english;
    }
}