using System.Globalization;

namespace AIVES.DTO.Localization;

/// <summary>
/// Translation catalog. English source text is the key and the fallback, so any key that is
/// missing here still renders in English instead of showing a resource identifier.
/// </summary>
internal static class AppText
{
    private static readonly Dictionary<string, string> Vietnamese = new(StringComparer.OrdinalIgnoreCase)
    {
        // Navigation and layout
        ["Work space"] = "Không gian làm việc",
        ["System"] = "Hệ thống",
        ["Overview"] = "Tổng quan",
        ["Questions & rubric"] = "Câu hỏi & rubric",
        ["Exams"] = "Kỳ thi",
        ["Under construction"] = "Đang xây dựng",
        ["AI exam room"] = "Phòng thi AI",
        ["Grading"] = "Chấm điểm",
        ["Reports"] = "Báo cáo",
        ["Users"] = "Người dùng",
        ["System check"] = "Kiểm tra hệ thống",
        ["Admin"] = "Quản trị",
        ["Data policy"] = "Chính sách dữ liệu",
        ["AI-powered Viva Exam System"] = "Hệ thống thi vấn đáp thông minh AI",
        ["AI-powered viva exam system"] = "Hệ thống thi vấn đáp thông minh có sử dụng AI",
        ["Secure access for lecturers and students"] = "Xác thực an toàn cho giảng viên và sinh viên",
        ["Sign in"] = "Đăng nhập",
        ["Sign out"] = "Đăng xuất",

        // Home
        ["Viva exam orchestration"] = "Điều hành thi vấn đáp",
        ["Prepare questions, run adaptive interviews and approve results in one auditable workflow."] = "Chuẩn bị câu hỏi, tổ chức phỏng vấn thích ứng và duyệt kết quả trong một quy trình có thể kiểm chứng.",
        ["Open bank"] = "Mở ngân hàng",
        ["Create question"] = "Tạo câu hỏi",
        ["Operating workflow"] = "Quy trình vận hành",
        ["From course material to grade decision"] = "Từ học liệu đến quyết định điểm",
        ["1 module ready"] = "1 module sẵn sàng",
        ["Question & rubric preparation"] = "Chuẩn bị câu hỏi & rubric",
        ["Create, classify Bloom level and approve questions before use."] = "Tạo, phân loại Bloom và duyệt câu hỏi trước khi sử dụng.",
        ["Ready"] = "Sẵn sàng",
        ["Planned"] = "Kế hoạch",
        ["Exam & scheduling"] = "Lập kỳ thi & lịch thi",
        ["Attach a subject, the participant list and a time limit."] = "Gắn môn học, danh sách sinh viên và giới hạn thời gian.",
        ["Adaptive interview"] = "Phỏng vấn thích ứng",
        ["STT, TTS and follow-up questions driven by the answer."] = "STT, TTS và câu hỏi đào sâu theo nội dung trả lời.",
        ["Grade review & evidence"] = "Duyệt điểm & bằng chứng",
        ["Reconcile transcript, rubric and the lecturer decision."] = "Đối chiếu transcript, rubric và quyết định của giảng viên.",
        ["The lecturer always decides"] = "Giảng viên luôn là người quyết định",
        ["Main question"] = "Câu hỏi chính",
        ["Choose by subject, Bloom level and rubric."] = "Chọn theo môn học, Bloom và rubric.",
        ["Answer recognition"] = "Nhận dạng câu trả lời",
        ["Turn speech into an auditable transcript."] = "Chuyển giọng nói thành transcript có lưu vết.",
        ["Adaptive probing"] = "Hỏi xoáy thích ứng",
        ["Clarify missing, vague or contradictory ideas."] = "Làm rõ ý thiếu, mơ hồ hoặc mâu thuẫn.",
        ["Rubric suggestions"] = "Gợi ý theo rubric",
        ["AI proposes; the lecturer approves and finalises the grade."] = "AI đề xuất; giảng viên duyệt và chốt điểm.",
        ["AIVES feature groups"] = "Các nhóm chức năng AIVES",
        ["Question bank"] = "Ngân hàng câu hỏi",
        ["CRUD for questions, Bloom levels and rubrics."] = "CRUD câu hỏi, mức Bloom và rubric.",
        ["Exams & scheduling"] = "Kỳ thi & lịch thi",
        ["Sessions, participants and question selection."] = "Phiên thi, thí sinh và chọn câu hỏi.",
        ["AI interview core"] = "Lõi phỏng vấn AI",
        ["STT, TTS and adaptive follow-up."] = "STT, TTS và adaptive follow-up.",
        ["Grading support"] = "Hỗ trợ chấm điểm",
        ["Reconcile transcripts against rubrics."] = "Đối chiếu transcript với rubric.",
        ["Supervision"] = "Giám sát",
        ["Recordings, logs and change history."] = "Bản ghi, log và lịch sử thay đổi.",
        ["Feedback & reports"] = "Phản hồi & báo cáo",
        ["Per question scores and class statistics."] = "Điểm từng câu và thống kê lớp.",
        ["Administration"] = "Quản trị",
        ["Accounts, permissions and language."] = "Tài khoản, phân quyền và ngôn ngữ.",

        // Account
        ["Resume your academic workspace"] = "Tiếp tục phiên làm việc học thuật",
        ["Access the question bank, AI exam room and assessment records with your verified account."] = "Truy cập ngân hàng câu hỏi, phòng thi AI và hồ sơ đánh giá bằng tài khoản đã xác minh.",
        ["Email is verified before sign in"] = "Email được xác minh trước khi đăng nhập",
        ["Temporary lock after repeated failed attempts"] = "Khóa tạm thời khi thử sai nhiều lần",
        ["Google OAuth never shares your password with AIVES"] = "Google OAuth không chia sẻ mật khẩu với AIVES",
        ["Use the Gmail account you registered with."] = "Nhập tài khoản Gmail đã đăng ký.",
        ["Password"] = "Mật khẩu",
        ["Enter your password"] = "Nhập mật khẩu",
        ["Keep me signed in on this device"] = "Ghi nhớ đăng nhập trên thiết bị này",
        ["or"] = "hoặc",
        ["Sign in with Google"] = "Đăng nhập với Google",
        ["No account yet?"] = "Chưa có tài khoản?",
        ["Register with Gmail"] = "Đăng ký bằng Gmail",
        ["Create an AIVES account"] = "Tạo tài khoản AIVES",
        ["Register"] = "Đăng ký",
        ["Register and send code"] = "Đăng ký và gửi mã",
        ["Use a Gmail address you can access."] = "Sử dụng địa chỉ Gmail bạn có quyền truy cập.",
        ["Full name"] = "Họ và tên",
        ["Confirm password"] = "Xác nhận mật khẩu",
        ["Continue with Google"] = "Tiếp tục với Google",
        ["Already have an account?"] = "Đã có tài khoản?",
        ["New account"] = "Tài khoản mới",
        ["Verified identity"] = "Xác thực danh tính",
        ["Email verification"] = "Xác minh email",
        ["Enter your verification code"] = "Nhập mã xác minh",
        ["A 6 digit code was sent to {0}. The code expires after 10 minutes."] = "Mã 6 chữ số đã được gửi đến {0}. Mã hết hạn sau 10 phút.",
        ["Verification code"] = "Mã xác minh",
        ["Verify account"] = "Xác minh tài khoản",
        ["Resend code"] = "Gửi lại mã",

        // Question bank
        ["Manage viva questions, Bloom taxonomy levels and scoring rubrics."] = "Quản lý câu hỏi vấn đáp, mức độ nhận thức và rubric đánh giá.",
        ["All questions"] = "Tất cả câu hỏi",
        ["{0} questions in the database"] = "{0} câu hỏi trong cơ sở dữ liệu",
        ["Question"] = "Câu hỏi",
        ["Topic"] = "Chủ đề",
        ["Bloom level"] = "Mức Bloom",
        ["Status"] = "Trạng thái",
        ["Actions"] = "Thao tác",
        ["View"] = "Xem",
        ["Edit"] = "Sửa",
        ["Delete"] = "Xóa",
        ["Active"] = "Hoạt động",
        ["Hidden"] = "Tạm ẩn",
        ["Created {0}"] = "Tạo ngày {0}",
        ["The bank has no questions yet"] = "Ngân hàng chưa có câu hỏi",
        ["Create your first structured viva question to get started."] = "Tạo câu hỏi vấn đáp có cấu trúc đầu tiên để bắt đầu.",
        ["Create the first question"] = "Tạo câu hỏi đầu tiên",
        ["Create a viva question"] = "Tạo câu hỏi vấn đáp",
        ["Write a clear question and attach its Bloom level and scoring rubric."] = "Xây dựng câu hỏi rõ ràng, gắn mức độ Bloom và rubric chấm điểm.",
        ["Can be generated with AI"] = "Có thể sinh bằng AI",
        ["Question content"] = "Nội dung câu hỏi",
        ["Enter the main question and the ideas the answer should cover."] = "Nhập câu hỏi chính và các ý cần có trong câu trả lời.",
        ["Viva question"] = "Câu hỏi vấn đáp",
        ["Example: Explain polymorphism and give one real world example."] = "Ví dụ: Hãy giải thích tính đa hình và đưa ra một ví dụ thực tế?",
        ["At least 10 characters. A good question targets one assessable capability."] = "Tối thiểu 10 ký tự. Câu hỏi nên tập trung vào một năng lực cần đánh giá.",
        ["Expected answer / key points"] = "Đáp án mong đợi / ý chính",
        ["List the concepts and key points the student should cover..."] = "Liệt kê khái niệm và các ý quan trọng mà sinh viên cần trình bày...",
        ["Assessment setup"] = "Khung đánh giá",
        ["Choose the Bloom level and how the answer will be scored."] = "Xác định mức độ nhận thức và phương pháp chấm điểm.",
        ["Scoring rubric"] = "Rubric chấm điểm",
        ["Select a Bloom level"] = "Chọn mức độ Bloom",
        ["Select a rubric"] = "Chọn rubric",
        ["Classification & status"] = "Phân loại & trạng thái",
        ["Attach a subject, topic and display order."] = "Gắn môn học, chủ đề và thứ tự hiển thị.",
        ["Subject / topic"] = "Môn học / chủ đề",
        ["Example: Object oriented programming"] = "Ví dụ: Lập trình hướng đối tượng",
        ["Display order"] = "Thứ tự hiển thị",
        ["Publish to the official bank"] = "Đưa vào ngân hàng chính thức",
        ["This question can be used in an examination"] = "Câu hỏi có thể được sử dụng trong kỳ thi",
        ["Cancel"] = "Hủy",
        ["Save question"] = "Lưu câu hỏi",
        ["Save changes"] = "Lưu thay đổi",
        ["Edit question"] = "Sửa câu hỏi",
        ["Refine the content or update its evaluation settings."] = "Chỉnh sửa nội dung hoặc cập nhật thiết lập đánh giá.",
        ["Keep the prompt clear and measurable."] = "Giữ câu hỏi rõ ràng và có thể đo lường.",
        ["Assessment & organization"] = "Đánh giá & tổ chức",
        ["Update taxonomy, rubric and classification."] = "Cập nhật phân loại, rubric và cách gom nhóm.",
        ["Active question"] = "Câu hỏi đang hoạt động",
        ["Available for use in examinations"] = "Có thể sử dụng trong kỳ thi",
        ["Question #{0}"] = "Câu hỏi #{0}",
        ["Question details"] = "Chi tiết câu hỏi",
        ["Review the complete assessment setup."] = "Xem lại toàn bộ thiết lập đánh giá.",
        ["Back"] = "Quay lại",
        ["● Active"] = "● Hoạt động",
        ["○ Hidden"] = "○ Tạm ẩn",
        ["Not specified"] = "Chưa xác định",
        ["Expected answer"] = "Đáp án mong đợi",
        ["Updated {0}"] = "Cập nhật {0}",
        ["Delete question"] = "Xóa câu hỏi",
        ["Delete this question?"] = "Xóa câu hỏi này?",
        ["This action is permanent and cannot be undone."] = "Hành động này là vĩnh viễn và không thể hoàn tác.",
        ["Keep question"] = "Giữ câu hỏi",
        ["Yes, delete permanently"] = "Có, xóa vĩnh viễn",

        // AI exam room
        ["Generate questions with Gemini"] = "Tạo câu hỏi bằng Gemini",
        ["Generate a viva question set"] = "Tạo bộ câu hỏi vấn đáp",
        ["Gemini produces a structured draft for the lecturer to read, refine and approve before it enters an exam."] = "Gemini tạo bản nháp có cấu trúc để giảng viên đọc, chỉnh sửa và duyệt trước khi đưa vào kỳ thi.",
        ["Academic brief"] = "Yêu cầu học thuật",
        ["Subject"] = "Môn học",
        ["Topic to assess"] = "Chủ đề cần đánh giá",
        ["Example: Polymorphism and SOLID"] = "Ví dụ: Tính đa hình và SOLID",
        ["Learning outcomes / knowledge scope"] = "Chuẩn đầu ra / phạm vi kiến thức",
        ["Describe the concepts, skills or content limits Gemini should follow..."] = "Nêu các khái niệm, kỹ năng hoặc giới hạn nội dung Gemini cần bám theo...",
        ["Number of questions"] = "Số câu hỏi",
        ["Difficulty"] = "Mức độ",
        ["Balanced"] = "Cân bằng",
        ["Basic"] = "Cơ bản",
        ["Intermediate"] = "Trung bình",
        ["Advanced"] = "Nâng cao",
        ["Generate list"] = "Tạo danh sách",
        ["Suggested list"] = "Danh sách đề xuất",
        ["{0} questions"] = "{0} câu",
        ["No questions generated yet"] = "Chưa có câu hỏi được tạo",
        ["Fill in the academic brief on the left. The result includes the main question, expected answer, Bloom level and two follow up questions."] = "Điền yêu cầu học thuật ở bên trái. Kết quả sẽ gồm câu hỏi chính, đáp án mong đợi, mức Bloom và hai câu hỏi đào sâu.",
        ["AI draft · needs lecturer approval"] = "Bản nháp AI · cần giảng viên duyệt",
        ["Expected key points"] = "Ý chính mong đợi",
        ["Follow up questions"] = "Câu hỏi đào sâu",

        // Admin system check
        ["System configuration check"] = "Kiểm tra cấu hình hệ thống",
        ["Aggregated status of external services and the database. This page is restricted to administrators."] = "Tổng hợp trạng thái các dịch vụ ngoài và database. Trang này chỉ dành cho quản trị viên.",
        ["System healthy"] = "Hệ thống ổn định",
        ["Configuration incomplete"] = "Có cấu hình còn thiếu",
        ["Check again"] = "Kiểm tra lại",
        ["Missing / errors"] = "Thiếu / lỗi",
        ["Configuration needed before the feature runs"] = "Cần cấu hình để tính năng chạy được",
        ["Warnings"] = "Cảnh báo",
        ["Optional, but worth reviewing"] = "Không bắt buộc nhưng nên kiểm tra",
        ["Configured"] = "Đã cấu hình",
        ["Services ready to use"] = "Dịch vụ sẵn sàng sử dụng",
        ["Service status"] = "Trạng thái từng dịch vụ",
        ["{0} checks"] = "{0} mục",
        ["How to fix"] = "Cách khắc phục",
        ["SQL Server data"] = "Dữ liệu SQL Server",
        ["Connected"] = "Đã kết nối",
        ["Disconnected"] = "Mất kết nối",
        ["Server"] = "Máy chủ",
        ["Database"] = "Cơ sở dữ liệu",
        ["Pending migrations"] = "Migration chưa áp dụng",
        ["Accounts with verified email"] = "Tài khoản đã xác minh email",
        ["Questions in the bank"] = "Câu hỏi trong ngân hàng",
        ["Rubrics / Bloom levels"] = "Rubric / Mức Bloom",
        ["Could not read data from SQL Server."] = "Không đọc được dữ liệu từ SQL Server.",
        ["Internal counters stay at 0 until the connection succeeds."] = "Các chỉ số nội bộ sẽ hiển thị 0 cho tới khi kết nối thành công.",
        ["Updated at {0} UTC · Environment {1}"] = "Cập nhật lúc {0} UTC · Môi trường {1}",

        // Data policy
        ["AIVES stores the academic data required to prepare and run viva examinations: account details, question banks, rubrics and assessment records."] = "AIVES lưu trữ dữ liệu học thuật cần thiết để chuẩn bị và vận hành kỳ thi vấn đáp: thông tin tài khoản, ngân hàng câu hỏi, rubric và hồ sơ đánh giá.",
        ["Access is limited to verified accounts. System configuration and service credentials are only visible to administrators."] = "Quyền truy cập chỉ dành cho tài khoản đã xác minh. Cấu hình hệ thống và thông tin dịch vụ chỉ hiển thị với quản trị viên.",

        // Sign in and account errors
        ["The email or password is incorrect, or the account has not been verified."] = "Email hoặc mật khẩu không đúng, hoặc tài khoản chưa được xác minh.",
        ["The email or password is incorrect."] = "Email hoặc mật khẩu không đúng.",
        ["The account is temporarily locked after too many failed sign in attempts."] = "Tài khoản tạm khóa do đăng nhập sai nhiều lần.",
        ["This account is not allowed to sign in or requires additional verification."] = "Tài khoản này không được phép đăng nhập hoặc cần xác thực bổ sung.",
        ["The account was not found."] = "Không tìm thấy tài khoản.",
        ["Please use a @gmail.com address."] = "Vui lòng sử dụng địa chỉ @gmail.com.",
        ["The verification code cannot be sent right now. Please try again later or contact an administrator."] = "Không thể gửi mã xác minh lúc này. Vui lòng thử lại sau hoặc liên hệ quản trị viên.",
        ["The verification code could not be sent. Please try again."] = "Không thể gửi mã xác minh. Vui lòng kiểm tra cấu hình Gmail và thử lại.",
        ["The code is incorrect, expired, or you exceeded the number of attempts."] = "Mã không đúng, đã hết hạn hoặc vượt quá số lần thử.",
        ["Could not read the Google sign in information."] = "Không nhận được thông tin đăng nhập Google.",
        ["This account is locked out, not allowed to sign in, or needs additional verification."] = "Tài khoản bị khóa, chưa được phép đăng nhập hoặc cần xác thực bổ sung.",
        ["Google did not provide an email address."] = "Google chưa cung cấp email.",
        ["Something went wrong while processing your account. Please try again."] = "Đã có lỗi khi xử lý tài khoản. Vui lòng thử lại.",
        ["If the account is valid, a new code has been sent."] = "Nếu tài khoản hợp lệ, một mã mới đã được gửi.",
        ["Could not send the verification code. Please try again."] = "Không thể gửi mã xác minh. Vui lòng thử lại.",
        ["Please wait a minute before requesting a new code."] = "Vui lòng chờ một phút trước khi yêu cầu mã mới.",

        // Email sender
        ["The email service is not configured."] = "Dịch vụ gửi email chưa được cấu hình.",
        ["Your AIVES account verification code"] = "Mã xác minh tài khoản AIVES",

        // Gemini
        ["The number of questions must be between 1 and 10."] = "Số câu hỏi phải từ 1 đến 10.",
        ["The subject must be between 1 and 120 characters."] = "Môn học phải có từ 1 đến 120 ký tự.",
        ["The topic must be between 1 and 200 characters."] = "Chủ đề phải có từ 1 đến 200 ký tự.",
        ["Learning outcomes cannot exceed 2000 characters."] = "Chuẩn đầu ra không được vượt quá 2000 ký tự.",
        ["Gemini cannot generate questions right now. Check the API key, quota and configured model."] = "Gemini không thể tạo câu hỏi lúc này. Hãy kiểm tra API key, quota và model cấu hình.",
        ["Gemini did not return a valid question list. Try again with a more specific topic."] = "Gemini chưa trả về danh sách câu hỏi hợp lệ. Vui lòng thử lại với chủ đề cụ thể hơn.",
        ["Could not generate questions right now. Please try again later."] = "Không thể tạo câu hỏi lúc này. Vui lòng thử lại sau.",
        ["The AI question generator is temporarily unavailable. Please try again later."] = "Tính năng tạo câu hỏi bằng AI đang tạm thời không khả dụng. Vui lòng thử lại sau.",
        ["Something went wrong while generating questions. Please try again."] = "Đã có lỗi khi tạo câu hỏi. Vui lòng thử lại.",

        // Profile
        ["Profile"] = "Hồ sơ",
        ["Your profile"] = "Hồ sơ của bạn",
        ["Your AIVES account details and sign out options."] = "Thông tin tài khoản AIVES và tùy chọn đăng xuất của bạn.",
        ["Account"] = "Tài khoản",
        ["Identity"] = "Danh tính",
        ["Email verified"] = "Email đã xác minh",
        ["Email not verified"] = "Email chưa xác minh",
        ["Member since"] = "Thành viên từ",
        ["Role"] = "Vai trò",
        ["User"] = "Người dùng",
        ["Session"] = "Phiên làm việc",
        ["Sign out ends the current session on this device and returns you to the login page."] = "Đăng xuất kết thúc phiên làm việc hiện tại trên thiết bị này và đưa bạn trở lại trang đăng nhập.",
        ["Something went wrong while loading the profile. Please try again."] = "Đã có lỗi khi tải hồ sơ. Vui lòng thử lại.",

        // Question bank
        ["An error occurred while retrieving questions"] = "Đã có lỗi khi tải danh sách câu hỏi.",
        ["An error occurred while loading the form"] = "Đã có lỗi khi tải biểu mẫu.",
        ["Question '{0}...' created successfully"] = "Đã tạo câu hỏi '{0}...' thành công.",
        ["Question updated successfully"] = "Đã cập nhật câu hỏi thành công.",
        ["Question deleted successfully"] = "Đã xóa câu hỏi thành công.",
        ["An error occurred while creating the question"] = "Đã có lỗi khi tạo câu hỏi.",
        ["An error occurred while updating the question"] = "Đã có lỗi khi cập nhật câu hỏi.",
        ["An error occurred while deleting the question"] = "Đã có lỗi khi xóa câu hỏi.",

        // Catalog: subjects, topics and material
        ["Subjects & topics"] = "Môn học & chủ đề",
        ["Materials"] = "Tài liệu",
        ["Catalog"] = "Danh mục",
        ["Manage subjects & topics"] = "Quản lý môn học & chủ đề",
        ["Add material"] = "Thêm tài liệu",
        ["Edit material"] = "Sửa tài liệu",
        ["Import material"] = "Nhập tài liệu",
        ["Import file"] = "Nhập tệp",
        ["Import"] = "Nhập",
        ["Uploaded material"] = "Tài liệu đã nhập",
        ["New subject"] = "Môn học mới",
        ["New topic"] = "Chủ đề mới",
        ["Add subject"] = "Thêm môn học",
        ["Add topic"] = "Thêm chủ đề",
        ["Subjects"] = "Môn học",
        ["Material"] = "Tài liệu",
        ["Material list"] = "Danh sách tài liệu",
        ["Material detail"] = "Chi tiết tài liệu",
        ["Material is stored per topic and becomes the grounding context for generated questions."] = "Tài liệu được lưu theo chủ đề và trở thành ngữ cảnh nền cho các câu hỏi được tạo ra.",
        ["The two levels above material. A question can point at a topic to inherit its material as context."] = "Hai cấp độ nằm trên tài liệu. Một câu hỏi có thể trỏ tới chủ đề để kế thừa tài liệu của chủ đề đó làm ngữ cảnh.",
        ["Reference content per topic. AI question generation grounds itself in this material."] = "Nội dung tham khảo theo tài liệu từng chủ đề. Việc tạo câu hỏi bằng AI sẽ dựa vào tài liệu này.",
        ["No topics yet"] = "Chưa có chủ đề nào",
        ["No subjects yet"] = "Chưa có môn học nào",
        ["No material for this selection"] = "Không có tài liệu cho lựa chọn này",
        ["No topics under this subject yet."] = "Chưa có chủ đề nào thuộc môn học này.",
        ["Material always belongs to a topic. Create a subject and topic first."] = "Tài liệu luôn thuộc về một chủ đề. Hãy tạo môn học và chủ đề trước.",
        ["Create a subject and topic before adding material."] = "Hãy tạo môn học và chủ đề trước khi thêm tài liệu.",
        ["Imported material needs a topic to live under."] = "Tài liệu nhập vào cần thuộc một chủ đề.",
        ["Add a subject first, then create topics under it."] = "Hãy thêm môn học trước, rồi tạo các chủ đề thuộc môn đó.",
        ["Add the subject you teach to start building topics and material."] = "Thêm môn học bạn đang giảng dạy để bắt đầu xây dựng chủ đề và tài liệu.",
        ["Add material manually or import a .txt, .md, .csv or .json file."] = "Thêm tài liệu thủ công hoặc nhập tệp .txt, .md, .csv hoặc .json.",
        ["Attach one rubric per question from the question editor."] = "Gắn một rubric cho mỗi câu hỏi từ trình chỉnh sửa câu hỏi.",
        ["Upload a plain text document and store it under a topic for question generation."] = "Tải lên một tài liệu văn bản thuần và lưu vào một chủ đề để tạo câu hỏi.",
        ["Upload a file"] = "Tải lên tệp",
        ["Store under topic"] = "Lưu vào chủ đề",
        ["File"] = "Tệp",
        ["Choose a file to import."] = "Hãy chọn một tệp để nhập.",
        ["The file is larger than 2 MB."] = "Tệp lớn hơn 2 MB.",
        ["Supported formats: .txt, .md, .csv, .json"] = "Định dạng hỗ trợ: .txt, .md, .csv, .json",
        ["max 2 MB"] = "tối đa 2 MB",
        ["The imported file does not contain enough text."] = "Tệp đã nhập không chứa đủ nội dung văn bản.",
        ["The file was imported as material."] = "Tệp đã được nhập thành tài liệu.",
        ["The file title becomes the material title, and its text is stored verbatim."] = "Tên tệp trở thành tiêu đề tài liệu và nội dung được lưu nguyên văn.",
        ["Originally imported from {0}."] = "Ban đầu được nhập từ {0}.",
        ["The material was added to the topic."] = "Đã thêm tài liệu vào chủ đề.",
        ["The material was updated."] = "Đã cập nhật tài liệu.",
        ["The material was deleted."] = "Đã xóa tài liệu.",
        ["The subject and everything under it was deleted."] = "Đã xóa môn học và toàn bộ nội dung bên dưới.",
        ["The topic and its material were deleted."] = "Đã xóa chủ đề và tài liệu của chủ đề đó.",
        ["The catalog was updated."] = "Đã cập nhật danh mục.",
        ["The catalog could not be updated. Please try again."] = "Không thể cập nhật danh mục. Vui lòng thử lại.",
        ["The material title must be between 2 and 300 characters."] = "Tiêu đề tài liệu phải có từ 2 đến 300 ký tự.",
        ["The material content must be at least 10 characters."] = "Nội dung tài liệu phải có ít nhất 10 ký tự.",
        ["The subject name must be between 2 and 200 characters."] = "Tên môn học phải có từ 2 đến 200 ký tự.",
        ["The topic name must be between 2 and 200 characters."] = "Tên chủ đề phải có từ 2 đến 200 ký tự.",
        ["Delete this material?"] = "Xóa tài liệu này?",
        ["Delete this topic and its material?"] = "Xóa chủ đề này và tài liệu của nó?",
        ["All subjects"] = "Tất cả môn học",
        ["All topics"] = "Tất cả chủ đề",
        ["Filter"] = "Lọc",
        ["Title"] = "Tiêu đề",
        ["Description"] = "Mô tả",
        ["Name"] = "Tên",
        ["Content"] = "Nội dung",
        ["Source"] = "Nguồn",
        ["Imported"] = "Đã nhập",
        ["Manual"] = "Thủ công",
        ["Characters"] = "Số ký tự",
        ["{0} items"] = "{0} mục",
        ["{0} characters"] = "{0} ký tự",
        ["{0} subjects"] = "{0} môn học",
        ["{0} topics"] = "{0} chủ đề",
        ["{0} material"] = "{0} tài liệu",
        ["Added {0}"] = "Đã thêm {0}",

        // AI generation panel: engines, grounding and rubric panel
        ["Engine"] = "Bộ sinh",
        ["AI generation"] = "Tạo câu hỏi bằng AI",
        ["Open generator"] = "Mở trình tạo câu hỏi",
        ["Open the generator panel, fill in the brief and choose an engine. The result includes the main question, expected answer, Bloom level and two follow up questions."] = "Mở bảng trình tạo, điền yêu cầu và chọn bộ sinh. Kết quả gồm câu hỏi chính, đáp án dự kiến, mức Bloom và hai câu hỏi đào sâu.",
        ["Gemini or the local Ollama model produces a structured draft for the lecturer to read, refine and approve."] = "Gemini hoặc mô hình Ollama cục bộ tạo ra bản nháp có cấu trúc để giảng viên đọc, tinh chỉnh và phê duyệt.",
        ["The result includes the main question, expected answer, Bloom level and two follow up questions."] = "Kết quả gồm câu hỏi chính, đáp án dự kiến, mức Bloom và hai câu hỏi đào sâu.",
        ["Automatic (recommended)"] = "Tự động (khuyến nghị)",
        ["Automatic prefers Gemini and falls back to the local Ollama model when Gemini has no API key."] = "Chế độ tự động ưu tiên Gemini và chuyển sang mô hình Ollama cục bộ khi Gemini chưa có API key.",
        ["· available"] = "· khả dụng",
        ["· local, available"] = "· cục bộ, khả dụng",
        ["· no API key"] = "· chưa có API key",
        ["· not running"] = "· chưa chạy",
        ["next engine"] = "bộ sinh tiếp theo",
        ["Ground the questions in material"] = "Dựa câu hỏi vào tài liệu",
        ["Retrieve material for the selected topic and use it as context"] = "Truy xuất tài liệu của chủ đề đã chọn và dùng làm ngữ cảnh",
        ["Catalog subject"] = "Môn học trong danh mục",
        ["Catalog topic"] = "Chủ đề trong danh mục",
        ["Grounded in {0} material items"] = "Dựa trên {0} mục tài liệu",
        ["Gemini is not available, so the local Ollama model was used instead."] = "Gemini không khả dụng nên đã dùng mô hình Ollama cục bộ thay thế.",
        ["Scoring"] = "Chấm điểm",
        ["Rubrics"] = "Rubric",
        ["Criteria"] = "Tiêu chí",
        ["Criterion"] = "Tiêu chí",
        ["Weight"] = "Trọng số",
        ["Score band"] = "Khoảng điểm",
        ["Close"] = "Đóng",
        ["Select a question to attach a rubric and its scoring criteria."] = "Chọn một câu hỏi để gắn rubric và các tiêu chí chấm điểm của nó.",
        ["Question #{0} is selected. Open the question to attach a rubric and criteria."] = "Đang chọn câu hỏi #{0}. Mở câu hỏi để gắn rubric và tiêu chí.",
        ["A rubric groups the levels a question can score at, so two lecturers grade the same answer consistently."] = "Rubric gom các mức điểm của một câu hỏi, giúp hai giảng viên chấm cùng một câu trả lời nhất quán.",
        ["Each criterion carries a weight, a description and a score band."] = "Mỗi tiêu chí có trọng số, mô tả và khoảng điểm.",
        ["The final score is the weighted sum of the matched bands."] = "Điểm cuối cùng là tổng có trọng số của các khoảng điểm được đạt.",
        ["Typical viva criteria: correctness, reasoning depth, terminology and example use."] = "Tiêu chí vấn đáp thường gặp: tính đúng đắn, chiều sâu lập luận, thuật ngữ và cách ví dụ.",
        ["Correctness of the answer"] = "Tính đúng đắn của câu trả lời",
        ["Reasoning and justification"] = "Lập luận và biện minh",
        ["Use of subject terminology"] = "Sử dụng thuật ngữ của môn học",
        ["Worked example or application"] = "Ví dụ minh họa hoặc áp dụng",
        ["Edit this question"] = "Sửa câu hỏi này",

        // AI provider diagnostics
        ["AI providers"] = "Bộ sinh AI",
        ["Neither Gemini nor Ollama is configured, so AI question generation is blocked."] = "Cả Gemini và Ollama đều chưa cấu hình nên không thể tạo câu hỏi bằng AI.",
        ["Gemini has no API key, so the local Ollama model ({0}) serves every request."] = "Gemini chưa có API key nên mô hình Ollama cục bộ ({0}) xử lý mọi yêu cầu.",
        ["Gemini is active with model {0}. Ollama is disabled, so there is no fallback."] = "Gemini đang hoạt động với mô hình {0}. Ollama đã tắt nên không có phương án dự phòng.",
        ["Gemini (model {0}) is active and Ollama ({1}) is the fallback. Active now: {2}."] = "Gemini (mô hình {0}) đang hoạt động và Ollama ({1}) là phương án dự phòng. Đang dùng: {2}.",
        ["Optional. Set Gemini:ApiKey to use Gemini and keep Ollama as a fallback."] = "Không bắt buộc. Đặt Gemini:ApiKey để dùng Gemini và giữ Ollama làm phương án dự phòng.",
        ["Optional. Set Ollama:Enabled to true so requests fall back to a local model when Gemini fails."] = "Không bắt buộc. Đặt Ollama:Enabled thành true để chuyển sang mô hình cục bộ khi Gemini thất bại.",
        ["(model not set)"] = "(chưa đặt mô hình)",
        ["The model did not return a valid question list. Try again with a more specific topic."] = "Mô hình không trả về danh sách câu hỏi hợp lệ. Hãy thử lại với chủ đề cụ thể hơn.",

        // Runtime diagnostics that previously fell back to English
        ["Could not connect to SQL Server."] = "Không thể kết nối tới SQL Server.",
        ["Check the SQL Server service and the ConnectionStrings:DefaultConnection value."] = "Kiểm tra dịch vụ SQL Server và giá trị ConnectionStrings:DefaultConnection.",
        ["{0}/{1} has {2} pending migrations: {3}."] = "{0}/{1} còn {2} migration chưa áp dụng: {3}.",
        ["The application has not finished migrating. Check the startup log or restart the application to apply migrations."] = "Ứng dụng chưa hoàn tất migration. Kiểm tra nhật ký khởi động hoặc khởi động lại ứng dụng để áp dụng.",
        ["{0}/{1} is connected and migrations are up to date."] = "{0}/{1} đã kết nối và các migration đã cập nhật.",
        ["Google sign in"] = "Đăng nhập bằng Google",
        ["ClientId/ClientSecret are not set, so Google sign in is disabled."] = "ClientId/ClientSecret chưa được đặt nên tính năng đăng nhập bằng Google bị tắt.",
        ["Optional. Set Authentication:Google:ClientId and ClientSecret to enable Google sign in."] = "Không bắt buộc. Đặt Authentication:Google:ClientId và ClientSecret để bật đăng nhập bằng Google.",
        ["Only one of ClientId/ClientSecret is set, so Google sign in still does not work."] = "Chỉ một trong ClientId/ClientSecret được đặt nên đăng nhập bằng Google vẫn chưa hoạt động.",
        ["Both Authentication:Google:ClientId and Authentication:Google:ClientSecret are required."] = "Cần cả Authentication:Google:ClientId và Authentication:Google:ClientSecret.",
        ["ClientId and ClientSecret are set."] = "ClientId và ClientSecret đã được đặt.",
        ["GmailSmtp:Username or GmailSmtp:AppPassword is not set, so verification codes cannot be sent and new accounts cannot be registered."] = "Chưa đặt GmailSmtp:Username hoặc GmailSmtp:AppPassword nên không thể gửi mã xác minh và không thể đăng ký tài khoản mới.",
        ["Mail is configured through {0}:{1} with the sender name {2}."] = "Thư được cấu hình qua {0}:{1} với tên người gửi {2}.",
        ["Runtime environment"] = "Môi trường chạy",
        ["Running the {0} environment."] = "Đang chạy môi trường {0}.",
        ["Running Production but the connection string still points at LocalDB, which will not work when deployed."] = "Đang chạy Production nhưng chuỗi kết nối vẫn trỏ tới LocalDB, điều này sẽ không hoạt động khi triển khai.",
        ["Set ConnectionStrings:DefaultConnection to an environment variable pointing at a real SQL Server."] = "Đặt ConnectionStrings:DefaultConnection trỏ tới một SQL Server thật.",
["Running the Production environment with an external connection string."] = "Đang chạy môi trường Production với chuỗi kết nối bên ngoài.",

        // Compact AI panel on the question pages
        ["AI assist"] = "Trợ giúp AI",
        ["Generate questions"] = "Tạo câu hỏi",
        ["Generate with AI"] = "Tạo bằng AI",
        ["Generate"] = "Tạo câu hỏi",
        ["Generating..."] = "Đang tạo...",
        ["Automatic"] = "Tự động",
        ["Ground in material"] = "Dựa vào tài liệu",
        ["Use catalog material as context"] = "Dùng tài liệu danh mục làm ngữ cảnh",
        ["Questions"] = "Số câu hỏi",
        ["no key"] = "chưa có key",
        ["not running"] = "chưa chạy",
        ["Use this question"] = "Dùng câu hỏi này",
        ["Filled in"] = "Đã điền",
        ["Copy"] = "Sao chép",
        ["Pick a result to fill the question form."] = "Chọn một kết quả để điền vào biểu mẫu câu hỏi.",
        ["No questions returned. Try a more specific topic."] = "Không có câu hỏi nào được trả về. Hãy thử với chủ đề cụ thể hơn.",
        ["Disabled"] = "Đang tắt",
        ["The AI exam room is disabled for now. Use the AI panel on the question pages."] = "AI exam room tạm thời đã bị tắt. Hãy dùng bảng trượt AI trên trang câu hỏi.",
        // Catalog page
        ["Topics"] = "Chủ đề",
        ["Topic name"] = "Tên chủ đề",
        ["Subject name"] = "Tên môn học",
        ["Search"] = "Tìm kiếm",
        ["Search subjects or topics"] = "Tìm kiếm môn học hoặc chủ đề",
        ["Search title or content"] = "Tìm theo tiêu đề hoặc nội dung",
        ["Clear"] = "Xóa bộ lọc",
        ["Save"] = "Lưu",
        ["Expand"] = "Mở rộng",
        ["Go to Subject tab"] = "Sang thẻ Môn học",
        ["Nothing matched your search"] = "Không có kết quả phù hợp",
        ["Try a different word, or clear the search to see everything."] = "Hãy thử từ khóa khác, hoặc xóa bộ lọc để xem tất cả.",
        ["No topics under this subject yet. Add one to hold material."] = "Môn học này chưa có chủ đề nào. Hãy thêm một chủ đề để chứa tài liệu.",
        ["Delete this subject and everything under it?"] = "Xóa môn học này và toàn bộ nội dung bên dưới?",
        ["Subjects and topics describe the course; material under a topic becomes the context AI questions are built from."] = "Môn học và chủ đề mô tả môn học; tài liệu thuộc chủ đề chính là ngữ cảnh để tạo câu hỏi AI.",

        // Question bank and rubric bank tabs
        ["Rubric bank"] = "Ngân hàng rubric",
        ["Question sections"] = "Các mục câu hỏi",
        ["Rubric sections"] = "Các mục rubric",
        ["Create"] = "Tạo mới",
        ["Bulk generation"] = "Tạo hàng loạt",
        ["Create a question"] = "Tạo câu hỏi",
        ["Create a rubric"] = "Tạo rubric",
        ["Create rubric"] = "Tạo rubric",
        ["New question"] = "Câu hỏi mới",
        ["New rubric"] = "Rubric mới",
        ["Open"] = "Mở",
        ["Draft"] = "Nháp",
        ["Published"] = "Đã xuất bản",
        ["Published only"] = "Chỉ hiện đã xuất bản",
        ["Total points"] = "Tổng điểm",
        ["Points"] = "Điểm",
        ["Count"] = "Số lượng",
        ["Keep"] = "Giữ",
        ["Note"] = "Ghi chú",
        ["Levels"] = "Mức độ",
        ["Level name"] = "Tên mức độ",
        ["Level columns"] = "Cột mức độ",
        ["Criterion rows"] = "Số hàng tiêu chí",
        ["Matrix"] = "Ma trận",
        ["Rubric"] = "Rubric",
        ["Attach rubric"] = "Gắn rubric",
        ["No rubric"] = "Không dùng rubric",
        ["With rubric"] = "Có rubric",
        ["Bloom levels used"] = "Số mức Bloom đã dùng",
        ["Assessment library"] = "Thư viện đánh giá",
        ["Active provider"] = "Nhà cung cấp đang dùng",
        ["How many"] = "Số lượng",
        ["Quick generate"] = "Tạo nhanh",
        ["Learning outcomes"] = "Mục tiêu học tập",
        ["Ground in catalog material"] = "Dựa trên tài liệu trong danh mục",
        ["Planned total"] = "Tổng đã kế hoạch",
        ["Add row"] = "Thêm hàng",
        ["Add column"] = "Thêm cột",
        ["Remove row"] = "Xóa hàng",
        ["Remove column"] = "Xóa cột",
        ["New column"] = "Cột mới",
        ["2 to 6 columns"] = "Từ 2 đến 6 cột",
        ["Up to 10 rows"] = "Tối đa 10 hàng",
        ["Start over"] = "Bắt đầu lại",
        ["Save to bank"] = "Lưu vào ngân hàng",
        ["Save rubric"] = "Lưu rubric",
        ["No AI provider available"] = "Không có nhà cung cấp AI khả dụng",
        ["Build it by hand instead"] = "Tự xây thay vì dùng AI",

        // Question bank copy
        ["Write questions by hand, generate them with AI, or plan a whole batch in bulk."] = "Viết câu hỏi bằng tay, tạo bằng AI, hoặc lập kế hoạch tạo cả lô.",
        ["All Bloom levels"] = "Tất cả mức Bloom",
        ["All rubrics"] = "Tất cả rubric",
        ["Search question text"] = "Tìm trong nội dung câu hỏi",
        ["Write one by hand, generate a set with AI, or plan a batch."] = "Tự viết, tạo bằng AI, hoặc lập kế hoạch hàng loạt.",
        ["{0} questions shown"] = "Đang hiển thị {0} câu hỏi",

        // AI generation tab
        ["Describe the questions"] = "Mô tả câu hỏi",
        ["AI drafts a set you can review before anything reaches the bank."] = "AI tạo sẵn bộ câu hỏi để bạn xem xét trước khi lưu vào ngân hàng.",
        ["What the candidates should be able to demonstrate"] = "Điều ứng viên cần thể hiện được",
        ["Need a whole batch? Use bulk"] = "Cần cả lô? Dùng tạo hàng loạt",
        ["Review before saving"] = "Xem xét trước khi lưu",
        ["{0} questions generated. Untick anything you do not want in the bank."] = "Đã tạo {0} câu hỏi. Bỏ chọn những câu bạn không muốn lưu vào ngân hàng.",
        ["Nothing was generated yet."] = "Chưa có nội dung nào được tạo.",
        ["{0} questions added to the bank"] = "Đã thêm {0} câu hỏi vào ngân hàng",
        ["Tick at least one question before saving."] = "Hãy chọn ít nhất một câu hỏi trước khi lưu.",
        ["An error occurred while saving a question."] = "Đã xảy ra lỗi khi lưu câu hỏi.",
        ["Could not match the generated Bloom level '{0}' to a level in the bank."] = "Không khớp được mức Bloom '{0}' với bất kỳ mức nào trong ngân hàng.",

        // Bulk generation tab
        ["Plan the batch"] = "Lập kế hoạch lô hàng",
        ["Say how many questions you need per Bloom level, then preview before saving."] = "Cho biết cần bao nhiêu câu theo từng mức Bloom, rồi xem trước trước khi lưu.",
        ["Coverage the batch should hit"] = "Nội dung mà lô hàng cần bao phủ",
        ["{0} of 30 questions"] = "{0} / 30 câu hỏi",
        ["Questions per Bloom level"] = "Số câu theo mức Bloom",
        ["Up to 10 per level and 30 in total."] = "Tối đa 10 câu mỗi mức và tổng cộng 30 câu.",
        ["No Bloom levels are configured yet."] = "Chưa cấu hình mức Bloom nào.",
        ["Preview the batch"] = "Xem trước lô hàng",
        ["Just a few? Use AI generation"] = "Chỉ cần vài câu? Dùng tạo bằng AI",
        ["A bulk plan must ask for between 1 and 30 questions."] = "Kế hoạch hàng loạt phải yêu cầu từ 1 đến 30 câu hỏi.",

        // Rubric bank and matrix editor
        ["Build a scoring matrix with your own rows and columns, or let AI draft one for you."] = "Xây ma trận chấm điểm với hàng và cột do bạn tự định nghĩa, hoặc để AI tạo giúp.",
        ["Stored matrices"] = "Ma trận đã lưu",
        ["{0} rubrics in the bank"] = "{0} rubric trong ngân hàng",
        ["Search rubrics or criteria"] = "Tìm rubric hoặc tiêu chí",
        ["Build a matrix by hand, or let AI draft one for you."] = "Tự xây ma trận, hoặc để AI tạo giúp bạn.",
        ["{0} rows × {1} columns"] = "{0} hàng × {1} cột",
        ["Highest total"] = "Tổng điểm cao nhất",
        ["Delete this rubric and its whole matrix?"] = "Xóa rubric này cùng toàn bộ ma trận của nó?",
        ["An error occurred while retrieving rubrics"] = "Đã xảy ra lỗi khi tải danh sách rubric",
        ["An error occurred while deleting the rubric"] = "Đã xảy ra lỗi khi xóa rubric",
        ["An error occurred while saving the rubric"] = "Đã xảy ra lỗi khi lưu rubric",
        ["Rubric deleted successfully"] = "Đã xóa rubric thành công",
        ["Rubric '{0}' saved successfully"] = "Đã lưu rubric '{0}' thành công",
        ["Rubric details"] = "Thông tin rubric",
        ["Name the matrix and say what it scores."] = "Đặt tên ma trận và mô tả nó chấm điều gì.",
        ["Name the scale. Points should rise from the weakest column to the strongest."] = "Đặt tên thang điểm. Điểm số nên tăng dần từ cột yếu nhất đến cột mạnh nhất.",
        ["What this level looks like"] = "Mức độ này trông như thế nào",
        ["Each row is scored independently and the row total is its best cell."] = "Mỗi hàng được chấm độc lập và tổng của hàng là giá trị cao nhất trong các ô của nó.",

        // Rubric AI generation
        ["Describe the matrix"] = "Mô tả ma trận",
        ["AI drafts the rows and the columns so you only have to correct them."] = "AI tạo sẵn các hàng và cột để bạn chỉ cần chỉnh sửa.",
        ["What the markers should be able to see"] = "Điều người chấm cần nhìn thấy",
        ["Draft a matrix"] = "Tạo dự thảo ma trận",
        ["Review the draft below, then save it to the bank."] = "Xem xét bản dự thảo bên dưới, rồi lưu vào ngân hàng.",
        ["{0} material items"] = "{0} mục tài liệu",
        ["The AI rubric generator is temporarily unavailable. Please try again later."] = "Trình tạo rubric bằng AI tạm thời không khả dụng. Vui lòng thử lại sau.",
        ["Could not generate a rubric right now. Please try again later."] = "Hiện chưa thể tạo rubric. Vui lòng thử lại sau.",
        ["Something went wrong while generating a rubric. Please try again."] = "Đã xảy ra sự cố khi tạo rubric. Vui lòng thử lại.",
        ["The model did not return a usable rubric matrix. Try again with a clearer topic."] = "Mô hình không trả về ma trận rubric phù hợp. Hãy thử lại với chủ đề cụ thể hơn.",
        ["Gemini cannot generate a rubric right now. Check the API key, quota and configured model."] = "Gemini hiện không thể tạo rubric. Kiểm tra API key, hạn mức và model đã cấu hình.",
        ["Ollama cannot generate a rubric right now. Confirm the local server is running and the model is pulled."] = "Ollama hiện không thể tạo rubric. Hãy xác nhận máy chủ cục bộ đang chạy và model đã được tải.",
        ["Ollama cannot generate questions right now. Confirm the local server is running and the model is pulled."] = "Ollama hiện không thể tạo câu hỏi. Hãy xác nhận máy chủ cục bộ đang chạy và model đã được tải.",
        ["No AI provider is available. Configure Gemini:ApiKey or enable the local Ollama model."] = "Không có nhà cung cấp AI khả dụng. Hãy cấu hình Gemini:ApiKey hoặc bật mô hình Ollama cục bộ.",
        ["The number of rows must be between 1 and 10."] = "Số hàng phải từ 1 đến 10.",
        ["A rubric matrix needs between 2 and 6 level columns."] = "Ma trận rubric cần từ 2 đến 6 cột mức độ.",

        // Registration copy that was still falling back to English
        ["Register with Gmail. AIVES sends a 6 digit code to confirm your address before the account is opened."] = "Đăng ký bằng Gmail. AIVES gửi mã 6 chữ số để xác nhận địa chỉ trước khi mở tài khoản.",
        ["The code is never stored in plain text"] = "Mã này không bao giờ được lưu dạng văn bản thuần",
        ["Verification code expires automatically"] = "Mã xác minh tự động hết hạn",
        ["Maximum number of wrong entries"] = "Số lần nhập sai tối đa"
    };

    public static string Resolve(string english)
    {
        if (string.IsNullOrEmpty(english))
            return english;

        if (CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.Equals("vi", StringComparison.OrdinalIgnoreCase)
            && Vietnamese.TryGetValue(english, out var translated))
            return translated;

        return english;
    }
}
